databases:
  - name: mysitedb
    plan: free
    databaseName: mysite
    user: mysite

services:
  - type: web
    plan: free
    name: morent2025
    runtime: python
    buildCommand: './backend/build.sh'
    startCommand: gunicorn Morent.asgi:application -k uvicorn.workers.UvicornWorker --chdir backend
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mysitedb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
    build:
      environment:
        pythonVersion: 3.11.9